name: ci

on:
  push:
    branches:
      - "master"

jobs:
  manylinux228_x86_64_with_deps-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push amd64
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          # This section is not necessary as this is the default in the Dockerfile,
          # Added to be explicit
          build-args: |
            ARCH=x86_64
            MANYLINUXIMG=manylinux_2_28
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/manylinux228_x86_64_with_deps:latest
  manylinux2014_x86_64_with_deps-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push amd64
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          # This section is not necessary as this is the default in the Dockerfile,
          # Added to be explicit
          build-args: |
            ARCH=x86_64
            MANYLINUXIMG=manylinux2014
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/manylinux2014_x86_64_with_deps:latest
